### ISSUE TITLE
`fab config list` giving errors, how to debug?

### ISSUE THREAD

**Issue by d34dman** [factorial-io/fabalicious#27]
`fab config list` giving errors, how to debug? Following is error output i get when i try to execute it.

    ElektronicsJunkyard: projectxyz [develop*] $ fab config list
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fabric/main.py", line 743, in main
        *args, **kwargs
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fabric/tasks.py", line 424, in execute
        results['<local-only>'] = task.run(*args, **new_kwargs)
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
        return self.wrapped(*args, **kwargs)
      File "/Users/myusername/work/mbb/projectxyz/fabfile.py", line 834, in config
        config = get_configuration(config_name)
      File "/Users/myusername/work/mbb/projectxyz/fabfile.py", line 357, in get_configuration
        config = get_all_configurations()
      File "/Users/myusername/work/mbb/projectxyz/fabfile.py", line 242, in get_all_configurations
        return load_configuration(start_folder + '/' + candidate)
      File "/Users/myusername/work/mbb/projectxyz/fabfile.py", line 191, in load_configuration
        if 'docker' in host and 'configuration' in host['docker']:
    TypeError: argument of type 'NoneType' is not iterable

Am using latest commit in the develop branch of fabalicious.

**Comment by stmh** [comment]
> if 'docker' in host and 'configuration' in host['docker']:

your host:docker:configuration-entry seems faulty.

**Comment by stmh** [comment]
the offending fable.yaml has an empty docker-key. Fabalicious should handle this with more grace.

**Comment by d34dman** [comment]
Thanks for figuring it out :)
