### ISSUE TITLE
Copy local DB 

### ISSUE THREAD

**Issue by MuschPusch** [factorial-io/fabalicious#34]
```
$ fab config:[...].clients.factorial.io restoreSQLFromFile:'backup/mbb--3abcd7a--2016-04-12--11-36-06.sql.gz'
[localhost] Executing task 'restoreSQLFromFile'
Establishing SSH-Tunnel... get remote ip-address ... Tunnel is established
Running task restoreSQLFromFilePrepare on configuration [...].clients.factorial.io
Running task restoreSQLFromFile on configuration [...].clients.factorial.io
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/rhizom/vagrant/projects/multibasebox/projects/optiks/fabfile.py", line 297, in restoreSQLFromFile
    methods.runTask(configuration.current(), 'restoreSQLFromFile', sourceFile = full_file_name)
  File "/Users/rhizom/vagrant/projects/multibasebox/projects/optiks/_tools/fabalicious/lib/methods/__init__.py", line 71, in runTask
    runTaskImpl(configuration['needs'], taskName, configuration, **kwargs);
  File "/Users/rhizom/vagrant/projects/multibasebox/projects/optiks/_tools/fabalicious/lib/methods/__init__.py", line 88, in runTaskImpl
    callImpl(methodName, taskName, configuration, True, **kwargs)
  File "/Users/rhizom/vagrant/projects/multibasebox/projects/optiks/_tools/fabalicious/lib/methods/__init__.py", line 47, in callImpl
    result = fn(configuration, **kwargs)
  File "/Users/rhizom/vagrant/projects/multibasebox/projects/optiks/_tools/fabalicious/lib/methods/drush.py", line 175, in restoreSQLFromFile
    put(sourceFile, targetSQLFileName)
  File "/usr/local/lib/python2.7/site-packages/fabric/network.py", line 649, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/operations.py", line 382, in put
    raise ValueError(err)
ValueError: 'backup/mbb--3abcd7a--2016-04-12--11-36-06.sql.gz' is not a valid local path or glob.
Disconnecting from localhost:2971... done.

```

**Comment by stmh** [comment]
I can't reproduce the issue. Perhaps it's an typo in your file-path? The standard backup-directory is named `backups`.
